package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type AlgoMetaResponse struct {
	Presets   interface{}      `json:"presets"`
	CodeLines []string         `json:"codeLines"`
	LineActive map[string][]int `json:"lineActive"`
}

var algoMetas = map[string]AlgoMetaResponse{
	"arrows": {
		Presets: []map[string]interface{}{
			{"points": [][]int{{10, 16}, {2, 8}, {1, 6}, {7, 12}}, "label": "Classic", "answer": 2},
			{"points": [][]int{{1, 2}, {3, 4}, {5, 6}, {7, 8}}, "label": "No overlap", "answer": 4},
			{"points": [][]int{{1, 6}, {2, 8}, {7, 12}, {10, 16}}, "label": "2 groups", "answer": 2},
			{"points": [][]int{{1, 2}, {2, 3}, {3, 4}, {4, 5}}, "label": "Touching", "answer": 2},
			{"points": [][]int{{-2147483646, -2147483645}, {2147483646, 2147483647}}, "label": "Extremes", "answer": 2},
		},
		CodeLines: []string{
			`func findMinArrowShots(points [][]int) int {`,
			`    sort.Slice(points, func(i,j int) bool {`,
			`        return points[i][1] < points[j][1]`,
			`    })`,
			`    arrows := 1`,
			`    currentEnd := points[0][1]`,
			`    for i := 1; i < len(points); i++ {`,
			`        if points[i][0] > currentEnd {`,
			`            arrows++`,
			`            currentEnd = points[i][1]`,
			`        }`,
			`    }`,
			`    return arrows`,
			`}`,
		},
		LineActive: map[string][]int{
			"sort":      {1, 2, 3},
			"init":      {4, 5},
			"check_hit": {6, 7},
			"hit":       {6, 7},
			"new_arrow": {7, 8, 9},
			"done":      {12},
		},
	},

	"calculator": {
		Presets: []map[string]interface{}{
			{"s": "1 + 1", "label": "Simple add", "answer": 2},
			{"s": " 2-1 + 2 ", "label": "Mixed signs", "answer": 3},
			{"s": "(1+(4+5+2)-3)+(6+8)", "label": "Nested ()", "answer": 23},
			{"s": "-(3+(4-2))", "label": "Leading neg", "answer": -5},
			{"s": "1-(5-(3+2))", "label": "Nested neg", "answer": 1},
		},
		CodeLines: []string{
			`stack := []int{}`,
			`result := 0; sign := 1`,
			`for i := 0; i < n; i++ {`,
			`    char := s[i]`,
			`    if char >= '0' && char <= '9' {`,
			`        num := 0`,
			`        for i<n && s[i]>='0' && s[i]<='9' {`,
			`            num = num*10 + int(s[i]-'0')`,
			`            i++`,
			`        }`,
			`        result += sign * num`,
			`        i--`,
			`    } else if char == '+' { sign = 1 }`,
			`    } else if char == '-' { sign = -1 }`,
			`    } else if char == '(' {`,
			`        stack = append(stack, result, sign)`,
			`        result = 0; sign = 1`,
			`    } else if char == ')' {`,
			`        prevSign   := stack[len-1]`,
			`        prevResult := stack[len-2]`,
			`        stack = stack[:len-2]`,
			`        result = prevResult + prevSign*result`,
			`    }`,
			`}`,
			`return result`,
		},
		LineActive: map[string][]int{
			"init":        {0, 1},
			"digit":       {4, 5, 6, 7, 8, 9, 10, 11},
			"plus":        {12},
			"minus":       {13},
			"open_paren":  {14, 15, 16},
			"close_paren": {17, 18, 19, 20, 21},
			"done":        {24},
		},
	},

	"candy": {
		Presets: []map[string]interface{}{
			{"ratings": []int{1, 0, 2}, "label": "Simple", "answer": 5},
			{"ratings": []int{1, 2, 2}, "label": "Tie", "answer": 4},
			{"ratings": []int{1, 3, 2, 2, 1}, "label": "Valley", "answer": 7},
			{"ratings": []int{1, 2, 3, 4, 5}, "label": "Ascending", "answer": 15},
			{"ratings": []int{5, 4, 3, 2, 1}, "label": "Descending", "answer": 15},
		},
		CodeLines: []string{
			`func candy(ratings []int) int {`,
			`    n := len(ratings)`,
			`    candies := make([]int, n)`,
			`    for i := range candies {`,
			`        candies[i] = 1`,
			`    }`,
			`    // Left → Right pass`,
			`    for i := 1; i < n; i++ {`,
			`        if ratings[i] > ratings[i-1] {`,
			`            candies[i] = candies[i-1] + 1`,
			`        }`,
			`    }`,
			`    // Right → Left pass`,
			`    for i := n - 2; i >= 0; i-- {`,
			`        if ratings[i] > ratings[i+1] {`,
			`        if candies[i] <= candies[i+1] {`,
			`            candies[i] = candies[i+1] + 1`,
			`        }`,
			`        }`,
			`    }`,
			`    total := 0`,
			`    for _, c := range candies {`,
			`        total += c`,
			`    }`,
			`    return total`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1, 2, 3, 4},
			"ltr_check":  {7, 8},
			"ltr_update": {8, 9},
			"ltr_skip":   {8},
			"rtl_check":  {13, 14},
			"rtl_update": {14, 15, 16},
			"rtl_skip":   {14},
			"sum":        {20, 21, 22},
			"done":       {24},
		},
	},

	"consecutive": {
		Presets: []map[string]interface{}{
			{"nums": []int{100, 4, 200, 1, 3, 2}, "label": "Classic", "answer": 4},
			{"nums": []int{0, 3, 7, 2, 5, 8, 4, 6, 0, 1}, "label": "Long run", "answer": 9},
			{"nums": []int{1, 2, 0, 1}, "label": "Dups", "answer": 3},
			{"nums": []int{9, 1, 4, 7, 3, -1, 0, 5, 8, -1, 6}, "label": "Negatives", "answer": 7},
		},
		CodeLines: []string{
			`func longestConsecutive(nums []int) int {`,
			`    set := make(map[int]struct{})`,
			`    for _, n := range nums { set[n] = {} }`,
			`    longest := 0`,
			`    for n := range set {`,
			`        if _, exists := set[n-1]; !exists {`,
			`            cur := n; streak := 1`,
			`            for {`,
			`                if _, ok := set[cur+1]; ok {`,
			`                    cur++; streak++`,
			`                } else { break }`,
			`            }`,
			`            if streak > longest {`,
			`                longest = streak`,
			`            }`,
			`        }`,
			`    }`,
			`    return longest`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1, 2, 3},
			"outer":      {4, 5},
			"skip":       {5},
			"start":      {5, 6},
			"extend":     {8, 9},
			"break_loop": {10},
			"update":     {12, 13},
			"no_update":  {12},
			"done":       {17},
		},
	},

	"container": {
		Presets: []map[string]interface{}{
			{"height": []int{1, 8, 6, 2, 5, 4, 8, 3, 7}, "label": "Classic", "answer": 49},
			{"height": []int{1, 1}, "label": "Minimal", "answer": 1},
			{"height": []int{4, 3, 2, 1, 4}, "label": "Symmetric", "answer": 16},
			{"height": []int{1, 2, 1}, "label": "Short", "answer": 2},
		},
		CodeLines: []string{
			`func maxArea(height []int) int {`,
			`    left := 0`,
			`    right := len(height) - 1`,
			`    maxWater := 0`,
			`    for left < right {`,
			`        width := right - left`,
			`        currentHeight := min(height[left], height[right])`,
			`        area := width * currentHeight`,
			`        if area > maxWater {`,
			`            maxWater = area`,
			`        }`,
			`        if height[left] < height[right] {`,
			`            left++`,
			`        } else {`,
			`            right--`,
			`        }`,
			`    }`,
			`    return maxWater`,
			`}`,
			``,
			`func min(a, b int) int {`,
			`    if a < b {`,
			`        return a`,
			`    }`,
			`    return b`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":         {1, 2, 3},
			"check_loop":   {4},
			"calc_width":   {5},
			"calc_height":  {6, 20, 21, 22},
			"calc_height_b":{6, 20, 21, 24},
			"calc_area":    {7},
			"new_max":      {8, 9},
			"no_max":       {8},
			"move_left":    {11, 12},
			"move_right":   {11, 14},
			"done":         {17},
		},
	},

	"cycle": {
		Presets: []map[string]interface{}{
			{"nodes": []int{3, 2, 0, -4}, "tail": 1, "label": "Has cycle", "answer": true},
			{"nodes": []int{1, 2}, "tail": 0, "label": "2-node cycle", "answer": true},
			{"nodes": []int{1}, "tail": -1, "label": "Single node", "answer": false},
			{"nodes": []int{1, 2, 3, 4, 5, 6}, "tail": 3, "label": "Long cycle", "answer": true},
			{"nodes": []int{1, 2, 3, 4, 5}, "tail": -1, "label": "No cycle", "answer": false},
		},
		CodeLines: []string{
			`func hasCycle(head *ListNode) bool {`,
			`    if head == nil || head.Next == nil {`,
			`        return false`,
			`    }`,
			`    slow := head`,
			`    fast := head.Next`,
			`    for fast != nil && fast.Next != nil {`,
			`        if slow == fast {`,
			`            return true  // cycle!`,
			`        }`,
			`        slow = slow.Next`,
			`        fast = fast.Next.Next`,
			`    }`,
			`    return false  // no cycle`,
			`}`,
		},
		LineActive: map[string][]int{
			"nil_check":  {1, 2},
			"init":       {4, 5},
			"check_meet": {6, 7},
			"met":        {7, 8},
			"advance":    {10, 11},
			"no_cycle":   {13},
			"done_true":  {8},
			"done_false": {13},
		},
	},

	"islands": {
		Presets: []map[string]interface{}{
			{
				"grid":   [][]string{{"1", "1", "1", "1", "0"}, {"1", "1", "0", "1", "0"}, {"1", "1", "0", "0", "0"}, {"0", "0", "0", "0", "0"}},
				"label":  "1 island",
				"answer": 1,
			},
			{
				"grid":   [][]string{{"1", "1", "0", "0", "0"}, {"1", "1", "0", "0", "0"}, {"0", "0", "1", "0", "0"}, {"0", "0", "0", "1", "1"}},
				"label":  "3 islands",
				"answer": 3,
			},
			{
				"grid":   [][]string{{"1", "0", "1", "0", "1"}, {"0", "1", "0", "1", "0"}, {"1", "0", "1", "0", "1"}},
				"label":  "Checkerboard",
				"answer": 9,
			},
			{
				"grid":   [][]string{{"1", "1", "1"}, {"0", "1", "0"}, {"1", "1", "1"}},
				"label":  "Ring",
				"answer": 1,
			},
		},
		CodeLines: []string{
			`func numIslands(grid [][]byte) int {`,
			`    count := 0`,
			`    for r := 0; r < rows; r++ {`,
			`        for c := 0; c < cols; c++ {`,
			`            if grid[r][c] == '1' {`,
			`                count++`,
			`                dfs(grid, r, c)`,
			`            }`,
			`        }`,
			`    }`,
			`    return count`,
			`}`,
			`func dfs(grid, r, c) {`,
			`    if outOfBounds || grid[r][c]=='0' {`,
			`        return`,
			`    }`,
			`    grid[r][c] = '0'  // sink`,
			`    dfs(r-1,c); dfs(r+1,c)`,
			`    dfs(r,c-1); dfs(r,c+1)`,
			`}`,
		},
		LineActive: map[string][]int{
			"scan":       {2, 3, 4},
			"new_island": {4, 5, 6},
			"dfs_enter":  {12, 13},
			"dfs_sink":   {16},
			"dfs_recurse":{17, 18},
			"dfs_base":   {13, 14},
			"done":       {10},
		},
	},

	"linkedcycle": {
		Presets: []map[string]interface{}{
			{"label": "Has cycle", "nodes": []int{3, 2, 0, -4}, "cyclePos": 1, "answer": "true"},
			{"label": "No cycle", "nodes": []int{1, 2, 3, 4, 5}, "cyclePos": -1, "answer": "false"},
			{"label": "Two nodes", "nodes": []int{1, 2}, "cyclePos": 0, "answer": "true"},
			{"label": "Self loop", "nodes": []int{1}, "cyclePos": 0, "answer": "true"},
		},
		CodeLines: []string{
			`func hasCycle(head *ListNode) bool {`,
			`    if head == nil || head.Next == nil {`,
			`        return false`,
			`    }`,
			`    slow := head`,
			`    fast := head.Next`,
			`    for fast != nil && fast.Next != nil {`,
			`        if slow == fast {`,
			`            return true`,
			`        }`,
			`        slow = slow.Next`,
			`        fast = fast.Next.Next`,
			`    }`,
			`    return false`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {4, 5},
			"loop_check": {6},
			"meet_check": {7},
			"found":      {7, 8},
			"advance":    {10, 11},
			"done_false": {13},
		},
	},

	"lis": {
		Presets: []map[string]interface{}{
			{"nums": []int{10, 9, 2, 5, 3, 7, 101, 18}, "label": "Classic", "answer": 4},
			{"nums": []int{0, 1, 0, 3, 2, 3}, "label": "Repeated", "answer": 4},
			{"nums": []int{7, 7, 7, 7, 7}, "label": "All same", "answer": 1},
			{"nums": []int{1, 3, 6, 7, 9, 4, 10, 5, 6}, "label": "Long", "answer": 6},
			{"nums": []int{3, 1, 4, 1, 5, 9, 2, 6}, "label": "Pi digits", "answer": 4},
		},
		CodeLines: []string{
			`tails := []int{}`,
			`for _, x := range nums {`,
			`    left, right := 0, len(tails)`,
			`    for left < right {`,
			`        mid := left + (right-left)/2`,
			`        if tails[mid] < x {`,
			`            left = mid + 1`,
			`        } else {`,
			`            right = mid`,
			`        }`,
			`    }`,
			`    if left == len(tails) {`,
			`        tails = append(tails, x)`,
			`    } else {`,
			`        tails[left] = x`,
			`    }`,
			`}`,
			`return len(tails)`,
		},
		LineActive: map[string][]int{
			"init":      {0},
			"start_num": {1, 2},
			"bisect":    {3, 4, 5, 6, 8},
			"go_right":  {5, 6},
			"go_left":   {7, 8},
			"extend":    {11, 12},
			"replace":   {13, 14},
			"done":      {17},
		},
	},

	"maxprofit": {
		Presets: []map[string]interface{}{
			{"prices": []int{3, 3, 5, 0, 0, 3, 1, 4}, "label": "Classic", "answer": 6},
			{"prices": []int{1, 2, 3, 4, 5}, "label": "Rising", "answer": 4},
			{"prices": []int{7, 6, 4, 3, 1}, "label": "Falling", "answer": 0},
			{"prices": []int{1, 2, 4, 2, 5, 7, 2, 4}, "label": "Two peaks", "answer": 8},
		},
		CodeLines: []string{
			`firstBuy  := -prices[0]`,
			`firstSell := 0`,
			`secondBuy := -prices[0]`,
			`secondSell := 0`,
			`for i := 1; i < len(prices); i++ {`,
			`    price := prices[i]`,
			`    if firstBuy < -price {`,
			`        firstBuy = -price`,
			`    }`,
			`    if firstSell < firstBuy+price {`,
			`        firstSell = firstBuy+price`,
			`    }`,
			`    if secondBuy < firstSell-price {`,
			`        secondBuy = firstSell-price`,
			`    }`,
			`    if secondSell < secondBuy+price {`,
			`        secondSell = secondBuy+price`,
			`    }`,
			`}`,
			`return secondSell`,
		},
		LineActive: map[string][]int{
			"init":      {0, 1, 2, 3},
			"update_fb": {6, 7},
			"update_fs": {9, 10},
			"update_sb": {12, 13},
			"update_ss": {15, 16},
			"scan":      {4, 5},
			"done":      {19},
		},
	},

	"maze": {
		Presets: []map[string]interface{}{
			{
				"maze": [][]int{
					{1, 0, 0, 0},
					{1, 1, 0, 1},
					{0, 1, 0, 0},
					{0, 1, 1, 1},
				},
				"label":  "4×4 Simple",
				"answer": 7,
			},
			{
				"maze": [][]int{
					{1, 1, 1, 1, 1},
					{0, 0, 0, 0, 1},
					{1, 1, 1, 0, 1},
					{1, 0, 0, 0, 1},
					{1, 1, 1, 1, 1},
				},
				"label":  "5×5 Spiral",
				"answer": 13,
			},
			{
				"maze": [][]int{
					{1, 0, 1, 1, 1},
					{1, 0, 1, 0, 1},
					{1, 1, 1, 0, 1},
					{0, 0, 0, 0, 1},
					{1, 1, 1, 1, 1},
				},
				"label":  "5×5 Alt",
				"answer": 9,
			},
			{
				"maze": [][]int{
					{1, 0},
					{0, 1},
				},
				"label":  "No path",
				"answer": -1,
			},
		},
		CodeLines: []string{
			`func solution(maze [][]int) int {`,
			`    visited := make([][]bool, m)`,
			`    queue   := []Cell{{0, 0, 1}}`,
			`    visited[0][0] = true`,
			`    for len(queue) > 0 {`,
			`        cur := queue[0]; queue = queue[1:]`,
			`        if cur.x == m-1 && cur.y == n-1 {`,
			`            return cur.dist`,
			`        }`,
			`        for _, d := range directions {`,
			`            nx, ny := cur.x+d[0], cur.y+d[1]`,
			`            if inBounds && !visited && maze==1 {`,
			`                visited[nx][ny] = true`,
			`                queue = append(queue, Cell{nx,ny,dist+1})`,
			`            }`,
			`        }`,
			`    }`,
			`    return -1`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":      {1, 2, 3},
			"dequeue":   {4, 5},
			"goal":      {6, 7},
			"neighbor":  {9, 10, 11},
			"enqueue":   {12, 13},
			"skip":      {11},
			"done_fail": {17},
		},
	},

	"merge": {
		Presets: []map[string]interface{}{
			{"a": []int{1, 3, 5}, "b": []int{2, 4, 6}, "label": "Interleaved"},
			{"a": []int{1, 2, 3}, "b": []int{4, 5, 6}, "label": "Non-overlap"},
			{"a": []int{1, 4, 7, 9}, "b": []int{2, 3, 8}, "label": "Asymmetric"},
			{"a": []int{5}, "b": []int{1, 2, 3, 4}, "label": "Single+many"},
		},
		CodeLines: []string{
			`func merge(a, b []int) []int {`,
			`    res := []int{}`,
			`    i, j := 0, 0`,
			`    for i < len(a) && j < len(b) {`,
			`        if a[i] <= b[j] {`,
			`            res = append(res, a[i]); i++`,
			`        } else {`,
			`            res = append(res, b[j]); j++`,
			`        }`,
			`    }`,
			`    res = append(res, a[i:]...)`,
			`    res = append(res, b[j:]...)`,
			`    return res`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1, 2},
			"loop":       {3},
			"compare":    {4},
			"pick_a":     {5},
			"pick_b":     {7},
			"leftover_a": {10},
			"leftover_b": {11},
			"done":       {12},
		},
	},

	"palindrome": {
		Presets: []map[string]interface{}{
			{"s": "A man, a plan, a canal: Panama", "label": "Classic", "answer": "true"},
			{"s": "race a car", "label": "Not palin", "answer": "false"},
			{"s": "Was it a car or a cat I saw?", "label": "Question", "answer": "true"},
			{"s": " ", "label": "Space", "answer": "true"},
		},
		CodeLines: []string{
			`func isPalindrome(s string) bool {`,
			`    left, right := 0, len(s)-1`,
			`    for left < right {`,
			`        lRune := rune(s[left])`,
			`        rRune := rune(s[right])`,
			`        if !unicode.IsLetter(lRune) && !unicode.IsDigit(lRune) {`,
			`            left++`,
			`            continue`,
			`        }`,
			`        if !unicode.IsLetter(rRune) && !unicode.IsDigit(rRune) {`,
			`            right--`,
			`            continue`,
			`        }`,
			`        if unicode.ToLower(lRune) != unicode.ToLower(rRune) {`,
			`            return false`,
			`        }`,
			`        left++`,
			`        right--`,
			`    }`,
			`    return true`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1},
			"check_loop": {2},
			"read_runes": {3, 4},
			"skip_left":  {5, 6, 7},
			"skip_right": {9, 10, 11},
			"compare":    {13},
			"mismatch":   {13, 14},
			"match":      {16, 17},
			"done_true":  {19},
			"done_false": {14},
		},
	},

	"reversewords": {
		Presets: []map[string]interface{}{
			{"s": "the sky is blue", "label": "Classic", "answer": `"blue is sky the"`},
			{"s": "  hello world  ", "label": "Trim spaces", "answer": `"world hello"`},
			{"s": "a good   example", "label": "Multi-space", "answer": `"example good a"`},
			{"s": "  Bob    Loves  Alice   ", "label": "Many spaces", "answer": `"Alice Loves Bob"`},
		},
		CodeLines: []string{
			`func reverseWords(s string) string {`,
			`    words := strings.Fields(s)`,
			`    left, right := 0, len(words)-1`,
			`    for left < right {`,
			`        words[left], words[right] =`,
			`            words[right], words[left]`,
			`        left++`,
			`        right--`,
			`    }`,
			`    return strings.Join(words, " ")`,
			`}`,
		},
		LineActive: map[string][]int{
			"init": {1, 2},
			"swap": {3, 4, 5, 6, 7},
			"done": {9},
		},
	},

	"rustbubble": {
		Presets: []map[string]interface{}{
			{"nums": []int{5, 3, 8, 1, 4}, "label": "Classic"},
			{"nums": []int{9, 7, 5, 3, 1}, "label": "Reversed"},
			{"nums": []int{1, 2, 3, 4, 5}, "label": "Sorted"},
			{"nums": []int{4, 2, 7, 1, 9, 3, 6}, "label": "Longer"},
		},
		CodeLines: []string{
			`fn bubble_sort(nums: &mut Vec<i32>) {`,
			`    let n = nums.len();`,
			`    for i in 0..n {`,
			`        let mut swapped = false;`,
			`        for j in 0..n - 1 - i {`,
			`            if nums[j] > nums[j + 1] {`,
			`                nums.swap(j, j + 1);`,
			`                swapped = true;`,
			`            }`,
			`        }`,
			`        if !swapped { break; }`,
			`    }`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1},
			"outer_loop": {2},
			"reset_swap": {3},
			"inner_loop": {4},
			"compare":    {5},
			"no_swap":    {5},
			"swap":       {6, 7},
			"pass_done":  {10},
			"early_exit": {10},
			"done":       {12},
		},
	},

	"rustlet": {
		Presets: []map[string]interface{}{
			{"nums": []int{1, 3, 5, 7, 9, 11, 13}, "target": 7, "label": "Classic"},
			{"nums": []int{2, 4, 6, 8, 10, 12, 14}, "target": 10, "label": "Even"},
			{"nums": []int{1, 2, 3, 4, 5}, "target": 6, "label": "Miss"},
			{"nums": []int{10, 20, 30, 40, 50}, "target": 10, "label": "First"},
			{"nums": []int{10, 20, 30, 40, 50}, "target": 50, "label": "Last"},
		},
		CodeLines: []string{
			`fn binary_search(nums: &[i32], target: i32) -> i32 {`,
			`    let mut lo = 0_usize;`,
			`    let mut hi = nums.len();`,
			`    while lo < hi {`,
			`        let mid = lo + (hi - lo) / 2;`,
			`        let val = nums[mid];`,
			`        if val == target { return mid as i32; }`,
			`        else if val < target { lo = mid + 1; }`,
			`        else                 { hi = mid; }`,
			`    }`,
			`    -1`,
			`}`,
		},
		LineActive: map[string][]int{
			"1": {1, 2},
			"2": {3},
			"3": {4, 5},
			"4": {6},
			"5": {7},
			"6": {8},
			"7": {10},
		},
	},

	"simplify": {
		Presets: []map[string]interface{}{
			{"path": "/home//foo/", "label": "Double slash", "answer": "/home/foo"},
			{"path": "/home/../usr/./bin", "label": "Up & dot", "answer": "/usr/bin"},
			{"path": "/../", "label": "Root up", "answer": "/"},
			{"path": "/a/./b/../../c/", "label": "Complex", "answer": "/c"},
			{"path": "/a/b/c/d/.../e", "label": "Triple dot", "answer": "/a/b/c/d/.../e"},
		},
		CodeLines: []string{
			`func simplifyPath(path string) string {`,
			`    parts := strings.Split(path, "/")`,
			`    stack := []string{}`,
			`    for _, part := range parts {`,
			`        if part == "" || part == "." {`,
			`            continue`,
			`        }`,
			`        if part == ".." {`,
			`            if len(stack) > 0 {`,
			`                stack = stack[:len(stack)-1]`,
			`            }`,
			`        } else {`,
			`            stack = append(stack, part)`,
			`        }`,
			`    }`,
			`    return "/" + strings.Join(stack, "/")`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":      {1, 2},
			"iter":      {3},
			"skip":      {4, 5},
			"check_up":  {7},
			"pop":       {8, 9},
			"pop_empty": {8},
			"push":      {11, 12},
			"done":      {15},
		},
	},

	"snakes": {
		Presets: []map[string]interface{}{
			{
				"label":  "Classic 6×6",
				"answer": 4,
				"board": [][]int{
					{-1, -1, -1, -1, -1, -1},
					{-1, -1, -1, -1, -1, -1},
					{-1, -1, -1, -1, -1, -1},
					{-1, 35, -1, -1, 13, -1},
					{-1, -1, -1, -1, -1, -1},
					{-1, 15, -1, -1, -1, -1},
				},
			},
			{
				"label":  "One ladder",
				"answer": 1,
				"board": [][]int{
					{-1, -1, -1},
					{-1, -1, -1},
					{-1, 9, -1},
				},
			},
			{
				"label":  "Blocked -1",
				"answer": -1,
				"board": [][]int{
					{-1, -1, -1},
					{-1, -1, 1},
					{-1, 1, -1},
				},
			},
		},
		CodeLines: []string{
			`queue := [][]int{{1, 0}}`,
			`visited[1] = true`,
			`for len(queue) > 0 {`,
			`    label, moves := dequeue()`,
			`    if label == target { return moves }`,
			`    for i := 1; i <= 6; i++ {`,
			`        next := label + i`,
			`        r,c := getCoords(next)`,
			`        if board[r][c] != -1 {`,
			`            destination = board[r][c]`,
			`        }`,
			`        if !visited[destination] {`,
			`            visited[destination] = true`,
			`            queue = append(queue, ...)`,
			`        }`,
			`    }`,
			`}`,
			`return -1`,
		},
		LineActive: map[string][]int{
			"init":         {0, 1},
			"dequeue":      {2, 3},
			"goal":         {4},
			"dice":         {5, 6, 7},
			"teleport":     {8, 9},
			"enqueue":      {11, 12, 13},
			"skip_visited": {11},
			"done_found":   {4},
			"done_fail":    {17},
		},
	},

	"substring": {
		Presets: []map[string]interface{}{
			{"s": "abcabcbb", "label": "Classic", "answer": 3},
			{"s": "bbbbb", "label": "All same", "answer": 1},
			{"s": "pwwkew", "label": "pwwkew", "answer": 3},
			{"s": "dvdf", "label": "dvdf", "answer": 3},
		},
		CodeLines: []string{
			`func lengthOfLongestSubstring(s string) int {`,
			`    lastSeen := make(map[rune]int)`,
			`    maxLength := 0`,
			`    left := 0`,
			`    for right, char := range s {`,
			`        if index, found := lastSeen[char]; found && index >= left {`,
			`            left = index + 1`,
			`        }`,
			`        lastSeen[char] = right`,
			`        maxLength = max(maxLength, right-left+1)`,
			`    }`,
			`    return maxLength`,
			`}`,
			``,
			`func max(a, b int) int {`,
			`    if a > b {`,
			`        return a`,
			`    }`,
			`    return b`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1, 2, 3},
			"move_right": {4},
			"check_in":   {5},
			"jump_left":  {6},
			"no_jump":    {5},
			"update_map": {8},
			"calc_max":   {9, 14, 15, 18},
			"new_max":    {9, 14, 15, 16},
			"done":       {11},
		},
	},

	"substring2": {
		Presets: []map[string]interface{}{
			{"s": "barfoothefoobarman", "words": []string{"foo", "bar"}, "label": "Classic", "answer": "[0,9]"},
			{"s": "wordgoodgoodgoodbestword", "words": []string{"word", "good", "best", "word"}, "label": "Dup word", "answer": "[]"},
			{"s": "barfoofoobarthefoobarman", "words": []string{"bar", "foo", "the"}, "label": "Multi", "answer": "[6,9,12]"},
			{"s": "lingmindraboofooowingdingbarrwingmonkeybaringoofoo", "words": []string{"fooo", "barr", "wing", "ding", "wing"}, "label": "Long", "answer": "[13]"},
		},
		CodeLines: []string{
			`func findSubstring(s string, words []string) []int {`,
			`    wordLen  := len(words[0])`,
			`    numWords := len(words)`,
			`    counts   := make(map[string]int)`,
			`    for _, w := range words { counts[w]++ }`,
			`    for i := 0; i < wordLen; i++ {`,
			`        left, count := i, 0`,
			`        currCounts  := make(map[string]int)`,
			`        for j := i; j <= len(s)-wordLen; j += wordLen {`,
			`            word := s[j : j+wordLen]`,
			`            if _, ok := counts[word]; ok {`,
			`                currCounts[word]++; count++`,
			`                for currCounts[word] > counts[word] {`,
			`                    leftWord := s[left:left+wordLen]`,
			`                    currCounts[leftWord]--; count--`,
			`                    left += wordLen`,
			`                }`,
			`                if count == numWords {`,
			`                    res = append(res, left)`,
			`                }`,
			`            } else {`,
			`                currCounts = make(map[string]int)`,
			`                count = 0; left = j + wordLen`,
			`            }`,
			`        }`,
			`    }`,
			`    return res`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1, 2, 3, 4},
			"outer_loop": {5, 6, 7},
			"inner_loop": {8, 9},
			"in_dict":    {10, 11},
			"shrink":     {12, 13, 14, 15},
			"found":      {17, 18},
			"no_found":   {17},
			"reset":      {20, 21, 22},
			"done":       {26},
		},
	},

	"sudoku": {
		Presets: []map[string]interface{}{
			{
				"label":  "Valid",
				"answer": "true",
				"board": [][]string{
					{"5", "3", ".", ".", "7", ".", ".", ".", "."},
					{"6", ".", ".", "1", "9", "5", ".", ".", "."},
					{".", "9", "8", ".", ".", ".", ".", "6", "."},
					{"8", ".", ".", ".", "6", ".", ".", ".", "3"},
					{"4", ".", ".", "8", ".", "3", ".", ".", "1"},
					{"7", ".", ".", ".", "2", ".", ".", ".", "6"},
					{".", "6", ".", ".", ".", ".", "2", "8", "."},
					{".", ".", ".", "4", "1", "9", ".", ".", "5"},
					{".", ".", ".", ".", "8", ".", ".", "7", "9"},
				},
			},
			{
				"label":  "Dup row",
				"answer": "false",
				"board": [][]string{
					{"8", "3", ".", ".", "7", ".", ".", ".", "."},
					{"6", ".", ".", "1", "9", "5", ".", ".", "."},
					{".", "9", "8", ".", ".", ".", ".", "6", "."},
					{"8", ".", ".", ".", "6", ".", ".", ".", "3"},
					{"4", ".", ".", "8", ".", "3", ".", ".", "1"},
					{"7", ".", ".", ".", "2", ".", ".", ".", "6"},
					{".", "6", ".", ".", ".", ".", "2", "8", "."},
					{".", ".", ".", "4", "1", "9", ".", ".", "5"},
					{".", ".", ".", ".", "8", ".", ".", "7", "9"},
				},
			},
			{
				"label":  "Dup box",
				"answer": "false",
				"board": [][]string{
					{"5", "3", ".", ".", "7", ".", ".", ".", "."},
					{"6", ".", ".", "1", "9", "5", ".", ".", "."},
					{".", "9", "5", ".", ".", ".", ".", "6", "."},
					{"8", ".", ".", ".", "6", ".", ".", ".", "3"},
					{"4", ".", ".", "8", ".", "3", ".", ".", "1"},
					{"7", ".", ".", ".", "2", ".", ".", ".", "6"},
					{".", "6", ".", ".", ".", ".", "2", "8", "."},
					{".", ".", ".", "4", "1", "9", ".", ".", "5"},
					{".", ".", ".", ".", "8", ".", ".", "7", "9"},
				},
			},
		},
		CodeLines: []string{
			`func isValidSudoku(board [][]byte) bool {`,
			`    var rows, cols, boxes [9][9]bool`,
			`    for r := 0; r < 9; r++ {`,
			`        for c := 0; c < 9; c++ {`,
			`            if board[r][c] == '.' { continue }`,
			`            num := board[r][c] - '1'`,
			`            boxIndex := (r/3)*3 + (c/3)`,
			`            if rows[r][num] || cols[c][num] ||`,
			`               boxes[boxIndex][num] {`,
			`                return false`,
			`            }`,
			`            rows[r][num]         = true`,
			`            cols[c][num]         = true`,
			`            boxes[boxIndex][num] = true`,
			`        }`,
			`    }`,
			`    return true`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":       {1},
			"skip":       {4},
			"read":       {5, 6},
			"check":      {7, 8},
			"conflict":   {7, 8, 9},
			"mark":       {11, 12, 13},
			"done_true":  {16},
			"done_false": {9},
		},
	},

	"twosum": {
		Presets: []map[string]interface{}{
			{"nums": []int{2, 7, 11, 15}, "target": 9, "label": "Classic"},
			{"nums": []int{3, 2, 4}, "target": 6, "label": "Middle"},
			{"nums": []int{1, 4, 6, 8, 3}, "target": 7, "label": "Longer"},
			{"nums": []int{5, 5}, "target": 10, "label": "Dupe"},
		},
		CodeLines: []string{
			`func twoSum(nums []int, target int) []int {`,
			`    seen := make(map[int]int)`,
			`    for i, num := range nums {`,
			`        needed := target - num`,
			`        if idx, ok := seen[needed]; ok {`,
			`            return []int{idx, i}`,
			`        }`,
			`        seen[num] = i`,
			`    }`,
			`    return nil`,
			`}`,
		},
		LineActive: map[string][]int{
			"1": {1},
			"2": {2},
			"3": {3},
			"4": {4, 5},
			"5": {7},
			"6": {9},
		},
	},

	"twosum2": {
		Presets: []map[string]interface{}{
			{"numbers": []int{2, 7, 11, 15}, "target": 9, "label": "Classic", "answer": "[1,2]"},
			{"numbers": []int{2, 3, 4}, "target": 6, "label": "Short", "answer": "[1,3]"},
			{"numbers": []int{-1, 0}, "target": -1, "label": "Negative", "answer": "[1,2]"},
			{"numbers": []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, "target": 11, "label": "Len 10", "answer": "[2,9]"},
		},
		CodeLines: []string{
			`func twoSum(numbers []int, target int) []int {`,
			`    left := 0`,
			`    right := len(numbers) - 1`,
			`    for left < right {`,
			`        sum := numbers[left] + numbers[right]`,
			`        if sum == target {`,
			`            return []int{left + 1, right + 1}`,
			`        }`,
			`        if sum < target {`,
			`            left++`,
			`        } else {`,
			`            right--`,
			`        }`,
			`    }`,
			`    return []int{}`,
			`}`,
		},
		LineActive: map[string][]int{
			"init":        {1, 2},
			"check_loop":  {3},
			"calc_sum":    {4},
			"found":       {5, 6},
			"cmp_sum":     {8},
			"move_left":   {8, 9},
			"move_right":  {8, 11},
			"done":        {6},
			"no_solution": {14},
		},
	},

	"wordsearch": {
		Presets: []map[string]interface{}{
			{
				"board":  [][]string{{"o", "a", "a", "n"}, {"e", "t", "a", "e"}, {"i", "h", "k", "r"}, {"i", "f", "l", "v"}},
				"words":  []string{"oath", "pea", "eat", "rain"},
				"label":  "Classic",
				"answer": `["eat","oath"]`,
			},
			{
				"board":  [][]string{{"a", "b"}, {"c", "d"}},
				"words":  []string{"abcb"},
				"label":  "No result",
				"answer": "[]",
			},
			{
				"board":  [][]string{{"o", "a", "n"}, {"t", "a", "e"}, {"i", "h", "k"}},
				"words":  []string{"oath", "eat", "tan", "nat"},
				"label":  "3×3 Multi",
				"answer": `["eat","oath"]`,
			},
		},
		CodeLines: []string{
			`// Build Trie`,
			`root := &TrieNode{}`,
			`for _, w := range words {`,
			`    node := root`,
			`    for _, char := range w {`,
			`        if node.children[idx] == nil {`,
			`            node.children[idx] = &TrieNode{}`,
			`        }`,
			`        node = node.children[idx]`,
			`    }`,
			`    node.word = w  // mark end`,
			`}`,
			`// DFS from each cell`,
			`backtrack(board, i, j, root, &res)`,
			`// In backtrack:`,
			`if node.children[idx] == nil { return }`,
			`nextNode := node.children[idx]`,
			`if nextNode.word != "" { res = append(res, word) }`,
			`board[r][c] = '#'  // mark visited`,
			`// recurse neighbors`,
			`backtrack(board, nr, nc, nextNode, res)`,
			`board[r][c] = char  // restore`,
		},
		LineActive: map[string][]int{
			"build_trie": {1, 2, 3, 4, 5, 6, 8, 10},
			"start_cell": {13},
			"no_child":   {15},
			"found_word": {16, 17},
			"mark":       {18},
			"recurse":    {19, 20},
			"restore":    {21},
			"done":       {},
		},
	},
}

func AlgoMetaHandler(c *gin.Context) {
	name := c.Param("name")
	meta, ok := algoMetas[name]
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "unknown algorithm: " + name})
		return
	}
	c.JSON(http.StatusOK, meta)
}
